// Generated by CoffeeScript 1.7.1
var __hasProp = {}.hasOwnProperty;

require(function() {
  var Action;
  return Action = (function() {
    Action.MOVE = 0;

    Action.MELEE = 1;

    Action.SHOOT = 2;

    function Action(id, data) {
      var k, v;
      this.id = id;
      if (data != null) {
        for (k in data) {
          v = data[k];
          this[k] = v;
        }
      }
    }

    Action.prototype.toJSON = function() {
      var k, res, v;
      res = {};
      for (k in this) {
        if (!__hasProp.call(this, k)) continue;
        v = this[k];
        res[k] = v.toString();
      }
      return res;
    };

    return Action;

  })();
});
