// Generated by CoffeeScript 1.7.1
(function() {
  globals.Terrain = {
    FLOOR: 0,
    WALL: 1,
    DOOR: 2,
    WATER: 3
  };
  globals.Feature = {
    BLOODY: 0
  };
  globals.INTERSECT_CHANCE = 1 / 8;
  return globals.ANIM_DURATION = 1000 / 6;
})();
