// Generated by CoffeeScript 1.7.1
require(function() {
  return $.fn.dragging = function(options) {
    if (options.start == null) {
      options.start = function() {
        return false;
      };
    }
    if (options.drag == null) {
      options.drag = function() {};
    }
    if (options.end == null) {
      options.end = function() {};
    }
    if (options.click == null) {
      options.click = function() {};
    }
    this.mousedown((function(_this) {
      return function(e) {
        var $doc, isDragging, startX, startY;
        if (e.which === 1) {
          e.preventDefault();
          startX = e.pageX;
          startY = e.pageY;
          isDragging = false;
          $doc = $(document).one('mouseup.dragging', function(e) {
            $doc.off('.dragging');
            if (isDragging) {
              return options.end(e);
            } else {
              return options.click(e, startX, startY);
            }
          }).on('mousemove.dragging', function(e) {
            var res;
            if (!isDragging) {
              res = options.start(e, startX, startY);
              if (res === false) {
                $doc.off('.dragging');
                return;
              }
              isDragging = true;
            }
            return options.drag(e);
          });
        }
      };
    })(this));
    return this;
  };
});
