// Generated by CoffeeScript 1.7.1
require(function(Equipment, Events) {
  var Inventory;
  return Inventory = (function() {
    Inventory.include(Events);

    function Inventory() {
      this.maxItems = 40;
      this.equipment = new Equipment;
      this.items = [];
      this.itemsCount = 0;
    }

    Inventory.prototype.isFull = function() {
      return this.itemsCount >= this.maxItems;
    };

    Inventory.prototype.add = function(it) {
      var i;
      i = this.findEmptySlot();
      if (i >= 0) {
        this.items[i] = it;
        this.itemsCount += 1;
        this.changed();
      }
    };

    Inventory.prototype.remove = function(it) {
      var i;
      i = this.items.indexOf(it);
      if (i >= 0) {
        this.items[i] = null;
        this.itemsCount -= 1;
        this.changed();
      }
    };

    Inventory.prototype.swapItem = function(it, id) {
      var res;
      if ((0 <= id && id < this.maxItems)) {
        res = this.items[id];
        this.items[id] = it;
        this.changed();
        return res;
      } else {
        return it;
      }
    };

    Inventory.prototype.findEmptySlot = function() {
      var i, _i, _ref;
      for (i = _i = 0, _ref = this.maxItems; 0 <= _ref ? _i < _ref : _i > _ref; i = 0 <= _ref ? ++_i : --_i) {
        if (this.items[i] == null) {
          return i;
        }
      }
      return -1;
    };

    Inventory.prototype.changed = function() {
      return this.trigger('change');
    };

    return Inventory;

  })();
});
