// Generated by CoffeeScript 1.7.1
require().defaults.path = "my";

require(function(defines, utils, Tiles) {
  var c, ctx, fl, pl, tiles;
  $('#content').html('<canvas id=c></canvas>');
  c = $('#c');
  ctx = getCanvasContext(c);
  tiles = new Tiles({
    tw: 48,
    th: 48,
    path: 'res/tiles'
  });
  ctx.tiles = tiles;
  fl = tiles.load('floor.png');
  pl = tiles.load('player.png');
  return tiles.onload(function() {
    var bluePl, redPl;
    bluePl = tiles.colorMask(pl, 'blue');
    redPl = tiles.colorMask(pl, 'red');
    ctx.drawTile(fl, 0, 0);
    ctx.drawTile(pl, 0, 0);
    ctx.globalAlpha = 0.5;
    ctx.drawTile(redPl, 0, 0);
    ctx.globalAlpha = 0.25;
    return ctx.drawTile(bluePl, 0, 0);
  });
});
