// Generated by CoffeeScript 1.7.1
require(function() {
  var Timeline;
  return Timeline = (function() {
    function Timeline() {
      this.time = 0;
      this.actors = [];
    }

    Timeline.prototype.add = function(actor) {
      this.actors.push(actor);
      return actor.time = this.time;
    };

    Timeline.prototype.remove = function(actor) {
      return this.actors = _.without(this.actors, actor);
    };

    Timeline.prototype.next = function() {
      var res;
      res = this.first();
      this.time = res.time;
      return res;
    };

    Timeline.prototype.first = function() {
      return _.min(this.actors, function(a) {
        return a.time;
      });
    };

    return Timeline;

  })();
});
