//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18052
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ChiitransLite.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "11.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Drawing.Rectangle location_MainForm {
            get {
                return ((global::System.Drawing.Rectangle)(this["location_MainForm"]));
            }
            set {
                this["location_MainForm"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Drawing.Rectangle location_TranslationForm {
            get {
                return ((global::System.Drawing.Rectangle)(this["location_TranslationForm"]));
            }
            set {
                this["location_TranslationForm"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string selectedPages {
            get {
                return ((string)(this["selectedPages"]));
            }
            set {
                this["selectedPages"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string lastRun {
            get {
                return ((string)(this["lastRun"]));
            }
            set {
                this["lastRun"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Drawing.Rectangle location_UserHookForm {
            get {
                return ((global::System.Drawing.Rectangle)(this["location_UserHookForm"]));
            }
            set {
                this["location_UserHookForm"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string okuriganaType {
            get {
                return ((string)(this["okuriganaType"]));
            }
            set {
                this["okuriganaType"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Drawing.Rectangle location_TextOptionsForm {
            get {
                return ((global::System.Drawing.Rectangle)(this["location_TextOptionsForm"]));
            }
            set {
                this["location_TextOptionsForm"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string translationDisplay {
            get {
                return ((string)(this["translationDisplay"]));
            }
            set {
                this["translationDisplay"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool clipboardTranslation {
            get {
                return ((bool)(this["clipboardTranslation"]));
            }
            set {
                this["clipboardTranslation"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string nonJpLocale {
            get {
                return ((string)(this["nonJpLocale"]));
            }
            set {
                this["nonJpLocale"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool nonJpLocaleAsk {
            get {
                return ((bool)(this["nonJpLocaleAsk"]));
            }
            set {
                this["nonJpLocaleAsk"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string cssTheme {
            get {
                return ((string)(this["cssTheme"]));
            }
            set {
                this["cssTheme"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool separateWords {
            get {
                return ((bool)(this["separateWords"]));
            }
            set {
                this["separateWords"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("[\"どうか\",\"二十年\",\"には\",\"ホン\",\"様な\",\"だと\",\"ものか\",\"内の者\",\"これ\",\"それ\",\"いいか\",\"お言葉\",\"ので\",\"のか\",\"そうも" +
            "ない\",\"有馬殿\",\"そうな\",\"のだ\",\"何がな\",\"てもいい\",\"ても\",\"じゃわ\",\"間に\",\"様に\",\"とも\",\"だの\",\"もので\",\"ないで\",\"声を" +
            "上げて\",\"タン\",\"話をした\",\"その子\",\"かっこ\",\"んとしてくれ\",\"らか\",\"たの\",\"今日は\",\"のです\",\"今来\",\"とけよ\",\"す\",\"事がない" +
            "\",\"ださいです\"]")]
        public string bannedWords {
            get {
                return ((string)(this["bannedWords"]));
            }
            set {
                this["bannedWords"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool transparentMode {
            get {
                return ((bool)(this["transparentMode"]));
            }
            set {
                this["transparentMode"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("70")]
        public double transparencyLevel {
            get {
                return ((double)(this["transparencyLevel"]));
            }
            set {
                this["transparencyLevel"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("100")]
        public double fontSize {
            get {
                return ((double)(this["fontSize"]));
            }
            set {
                this["fontSize"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool atlasAsk {
            get {
                return ((bool)(this["atlasAsk"]));
            }
            set {
                this["atlasAsk"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"[""はま"",""だいちゃって"",""こって"",""とのご"",""さんや"",""こっか"",""してい"",""わけない"",""すって"",""いよ"",""につき"",""ような"",""とけよ"",""かされました"",""どうか"",""ある"",""しょう"",""のバラ"",""もんだ"",""ことに"",""もと"",""たから"",""はご"",""にご"",""とがないで"",""とご"",""あんたい"",""くらい"",""うちに"",""わけないで"",""かな"",""うご"",""とお"",""かがされました"",""すね"",""ちらから"",""そうし"",""るか"",""らか"",""ました"",""なのか"",""はやめません"",""ないや"",""はいる"",""さんが"",""らい"",""はもう"",""はいかん"",""そうこ"",""なら"",""したん"",""ことし"",""そうなん"",""さんがして"",""ないといけない"",""そうな"",""ほうがい"",""いわ"",""になってから"",""われてなくて"",""きと"",""かと"",""がなって"",""さと"",""いいん"",""そこに"",""のか"",""ないといけな"",""カッコして"",""す"",""いか"",""もが"",""おか"",""にい"",""からぬ"",""たいよ"",""ともない"",""もとは"",""ござい"",""うなら"",""いなら"",""うなったら"",""にそう"",""はどう"",""カッコし"",""たばかり"",""さんがし"",""くり"",""けそう"",""ろうか"",""ましたら"",""はこ"",""どうかされました"",""いるか"",""あるか"",""にない"",""とない"",""もお"",""ござ"",""ないと"",""うかされました"",""こない"",""みにいってた"",""これは"",""ろう""]")]
        public string bannedWordsKana {
            get {
                return ((string)(this["bannedWordsKana"]));
            }
            set {
                this["bannedWordsKana"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool ieUpgradeAsk {
            get {
                return ((bool)(this["ieUpgradeAsk"]));
            }
            set {
                this["ieUpgradeAsk"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool separateSpeaker {
            get {
                return ((bool)(this["separateSpeaker"]));
            }
            set {
                this["separateSpeaker"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Drawing.Rectangle location_HookOptionsForm {
            get {
                return ((global::System.Drawing.Rectangle)(this["location_HookOptionsForm"]));
            }
            set {
                this["location_HookOptionsForm"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string selectedReadings {
            get {
                return ((string)(this["selectedReadings"]));
            }
            set {
                this["selectedReadings"] = value;
            }
        }
    }
}
